[package]
name = "vulkano-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
vulkano = "0.34.0"
vulkano-shaders = "0.34.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[profile.dev]
# opt-level = 1
